site_name: Web estàtica amb mkdocs
docs_dir: 'md'
site_dir: 'docs'
dev_addr: localhost:4000
nav:
  - Introducció i  intal·lació: introduccio.md
  - Configuració: configuracio.md
  - Allotgem la web a Aules: aules.md
  - Allotgem la web a github: github.md
  - "Docència: Aules o github?": aules vs github.md

markdown_extensions:
  - admonition
  - attr_list         # permet afegir atributs a les etiquetes html 
  # pymdownx és una col·leccio per escritura tècnica. S'instal·la per defecte
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      auto_title: true
  - pymdownx.emoji: 
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme: 
  name: material  # selecció del tema
  palette:
   # Boto que canvia a mode oscur
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Botó que canvia a mode clar
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # utilitats de copia de codi
    - content.code.copy 
    - content.code.select
    - content.code.annotate
    - navigation.footer       # footer de la pagina, amb navegació
    - navigation.top    # boto flotant de tornar a dalt 


plugins:
  - search      # plugin del quadre cerca
#  - pdf-export  # plugin per exportar a pdf